apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qlkube.fullname" . }}-harbor-token
  labels:
    {{- include "qlkube.labels" . | nindent 4 }}
type: Opaque
stringData:
  harbor_token.json: |
    {{ .Values.harborToken | toJson | indent 4 }}
